// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgMnhiLtAowbKv4WFe3NDZE1UuYk0Dk0k',
    appId: '1:874181377171:web:159ad6b4b9708f1848a166',
    messagingSenderId: '874181377171',
    projectId: 'live-score-app-cfb78',
    authDomain: 'live-score-app-cfb78.firebaseapp.com',
    storageBucket: 'live-score-app-cfb78.firebasestorage.app',
    measurementId: 'G-N1LB66E10R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArMwoWdnG17UUgxPlVkJEaPz60VAZ3xX0',
    appId: '1:874181377171:android:d142a8f6c835617248a166',
    messagingSenderId: '874181377171',
    projectId: 'live-score-app-cfb78',
    storageBucket: 'live-score-app-cfb78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvVS7bXDeuPtWzl69b_Sgxs4zbziihAQM',
    appId: '1:874181377171:ios:16f7ce470b7ecad048a166',
    messagingSenderId: '874181377171',
    projectId: 'live-score-app-cfb78',
    storageBucket: 'live-score-app-cfb78.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreApp',
  );

}